version: '2'
services:
  app:  
    image: node-chat
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
