version: '2'
services:
  app:
    build:
        context: containers/nodejs/
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/src/"
    links:
      - db
  db:
    image: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
